# Iniciar o Minikube
start:
	minikube start

# Gerar o service da DB
gen_db_service_yaml:
	kubectl create service clusterip database \
  --tcp=5432:5432 \
  --dry-run=client -o yaml > infra/database/database_service.yaml

# Gerar o deployment YAML da API
gen_api_deployment_yaml:
	kubectl create deployment api --image cstrader:latest --replicas 3 --port=8000 --dry-run=client -o yaml > infra/backend/api_deployment.yaml

# Gerar o service YAML da API
gen_api_service_yaml:
	kubectl create service loadbalancer api \
  --tcp=8000:8000 \
  --dry-run=client -o yaml > infra/backend/api_service.yaml

#Gerar o deployment frontend
gen_frontend_deployment_yaml:
	kubectl create deployment frontend --image cstrader_nginx --replicas 3 --port=3000 --dry-run=client -o yaml > infra/frontend/frontend_deployment.yaml

#Gerar o service frontend
gen_frontend_service_yaml:
kubectl create service loadbalancer frontend \
  --tcp=3000:3000 \
  --dry-run=client -o yaml > ingra/frontend/frontend_service.yaml

# Aplicar os secrets
secrets:
	kubectl apply -f secret.yaml

# Aplicar a Base de Dados (statefulset + Service)
db:
	kubectl apply -f infra/database/database_statefulset.yaml
	kubectl apply -f infra/database/database_service.yaml

# Aplicar a API (Deployment + Service)
api:
	kubectl apply -f backend/api_deployment.yaml
	kubectl apply -f backend/api_service.yaml

# Aplicar o Frontend (Deployment + Service)
frontend:
	# 1. Cria o ConfigMap a partir da tua pasta local
	kubectl create configmap nginx-conf --from-file=frontend/conf.d/ --dry-run=client -o yaml | kubectl apply -f -
	# 2. Aplica o Deployment e Service
	kubectl apply -f infra/frontend/frontend_deployment.yaml
	kubectl apply -f infra/frontend/frontend_service.yaml

#frontend: 
#	./scripts/frontend_apply.shg

#ingress
ingress: 
	kubectl create ingress cstrader-ingress \
	--class=nginx \
	--rule="cstrader.local/api=api:8000" \
	--rule="cstrader.local/=frontend:3000" \
	--annotation="nginx.ingress.kubernetes.io/rewrite-target=/" \
	--dry-run=client -o yaml > ingress.yaml

# Ligar tudo de uma vez
all: secrets db api frontend
	@echo "Tudo ligado! 🚀"

# Apagar tudo
clean:
	kubectl delete -f api_service.yaml --ignore-not-found=true
	kubectl delete -f api_deployment.yaml --ignore-not-found=true
	kubectl delete -f database_service.yaml --ignore-not-found=true
	kubectl delete -f database_deployment.yaml --ignore-not-found=true
	kubectl delete -f storage.yaml --ignore-not-found=true
	kubectl delete -f secret.yaml --ignore-not-found=true